# 访问端口
server:
  port: 18080

# dubbo服务消费者配置
dubbo:
  application:
    name: tanhua-server
  registry:
    address: zookeeper://192.168.12.160:2181

tanhua:
  sms:
    signName: 袁小杰
    templateCode: SMS_99320050
    accessKey: LTAI6oNQblwg4mjc
    secret: pBJAfwYp0bo4EZWiBA5LfOK1qgMHln

spring:
  redis:
    host: 192.168.12.160
    port: 6379